### ISSUE TITLE
How can i run in WSgi? please help

### ISSUE THREAD

**Issue by indexmefastcom** [ytrevor81/TradingView-Binance-Telegram-Bot#9]
How can i run in WSgi? please help

**Comment by ytrevor81** [comment]
To run any program thru WSGI there's a lot of documentation and tutorials on how to do it properly. I know this isn't an ideal answer to your question, but there's many other resources out there that can explain it much better than i can.

Also WSGI is not specific to this project, it's a different topic since it's a standard procedure for most Python applications to run on a remote server. It's not unique to this project. So i'll have to mark this issue as closed.
